### ISSUE TITLE
Microsoft.Dynamics365.UIAutomation.Api.9.0.1.6 not found

### ISSUE THREAD

**Issue by sventepe** [ewingjm/development-hub#3]
Hi,

I got problems restoring the nuget packages, as Microsoft.Dynamics365.UIAutomation.Api.9.0.1.6 seems to be unavailable on nuget.

How can I fix this?

Regards

Sven

**Comment by sventepe** [comment]
Got it working by removing Microsoft.Dynamics365.UIAutomation.Api and updating Dynamics365.UIAutomation.Api to the latest version :)

**Comment by ewingjm** [comment]
Hi, @sventepe. Thanks for letting me know and feel free to create a pull request for your fix unless I get to it before you do 🙂
