### ISSUE TITLE
Yeoman generator missing

### ISSUE THREAD

**Issue by sventepe** [ewingjm/development-hub#4]
Hi Max,

I'm currently trying to get the Alpha up and running. My progress is good so far, I can not find the Yeoman generator though. I did search yeoman.io and "yo" for "Common Data Service", is that correct?

Regards

Sven

**Comment by ewingjm** [comment]
Hi, @sventepe. Apologies - you're correct. I forgot to remove this part of the documentation before moving the repository to GitHub. The Yeoman generator hasn't been published to the public npm registry and yet and is still an internal Capgemini tool. I'm working to make this available on the public registry.

I've added a public email address to my GitHub profile - if you want to get in touch I'm happy to help you get this set up.

**Comment by ewingjm** [comment]
Removed this from the documentation.
