### ISSUE TITLE
Allow Solution Merge Approver to confirm Manual Steps are complete

### ISSUE THREAD

**Issue by tdashworth** [ewingjm/development-hub#81]
**Is your feature request related to a problem? Please describe.**
On our project, the user approving the Solution Merge will often also carry out the manual steps (documented in a Note). The problem is that only the creator of the Solution Merge Request can confirm these have been done via an Approval. 

**Describe the solution you'd like**
I would like both the creator and approver to be added to the Approvers list where either one of them can confirm it.

**Comment by ewingjm** [comment]
Hi @tdashworth. We've had the same issue on DEFRA. In some instances the only person that can approve the manual steps is on annual leave. We ended up setting the solution merge back to awaiting approval and approving it again without manual merge activities checked. Bit of a nightmare.
